HOTFIX: Add support for specifying extraction source as CLI argument
health-lake/hl-extractions pull request #11
Opened 2021-05-24 02:39 UTC by rennanharo

# Context
We must be able to run each extraction individually.
As we're planning a major refactor of the whole extractions module, to deliver this feature ASAP I've introduced a hotfix to allow us to run each extraction individually simply by specifying which one to run as a CLI argument.
Example: `python main.py CNAC`.

# Proposed changes
Add a CLI argument checker to the script that will "orchestrate" each extraction according to the sources passed in as parameters.

The values accepted as arguments are: `CNAC`, `RCIV` or `SRAG`.
If the parameter fails to suffice any of the conditions, an error will be raised.

**NOTE: THIS IS A TEMPORARY FIX**

# Types of changes
- [ ] Feature improvement (non-breaking change which improves an existing functionality)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)
- [x] Hotfix (unexpected change which fixes an issue as an emergency response to an event or incident)
- [ ] Bugfix (non-breaking change which fixes an issue)

2021-05-24 10:46 UTC, brbraziel commented
Achei bem interessante o que você fez pra que ficasse mais fácil de reutilizar o código. Gostaria de fazer 2 sugestões e podemos discutir sobre:

1. Se chamássemos esse aquivo main.py de extractions_central.py, uma vez que ele seria um intermediador entre todos os extratores, e seria bem mais fácil de, em um futuro, quando isso for documentado, entender o propósito do arquivo.
2. Se criássemos um arquivo JSON passando as chaves permitidas (CNAC, RCIV e SRAG), com seus valores sendo a chamada dos métodos. Dessa forma, conforme nossas extrações forem expandindo, poderíamos apenas popular este json sem ter que tocar no código. 

Caso tenha ficado muito confuso, a gente pode bater um papo melhor sobre!

2021-05-25 10:36 UTC, davikawasaki requested changes
Well done. Just complementing @brbraziel suggestion with some recommended code. Bear in mind that I'm not a python developer, so there might be errors along the way :)

2021-05-25 10:36 UTC, davikawasaki commented on extractors/main.py
> +        srag.download()
I'm down with @brbraziel suggestion. This way we can make it generic and avoid an overload of conditionals in here:

```suggestion
import json
import os
import importlib.util

def main(source_path, source_args):
    try:
       source_name = os.path.splitext(os.path.basename(source_path))[0]
       spec = importlib.util.spec_from_file_location(source_name, source_path)
       module = importlib.util.module_from_spec(spec)
       module_inst = module(*source_args)
       module_inst.download()
    except:
       print('dynamic import not successful')
```

2021-05-25 10:36 UTC, davikawasaki commented on extractors/main.py
> +        srag.download()
Just the idea here, I didn't test to see if this dynamic import works, especially with **multiple args**.

2021-05-25 10:36 UTC, davikawasaki commented on extractors/main.py
> +    main(sys.argv[1].upper())
JSON structure:

```json
{
    "CNAC": {
       "source_path": "caminho/do/arquivo/cnac.py",
       "source_args": null
    },
    "RCIV": {
       "source_path": "caminho/do/arquivo/rciv.py",
       "source_args": ["2021-01-01 00:00:00", "2021-02-28 00:00:00"]
    }
} 
```

```suggestion
    with open('path_to_file/dict.json') as f:
       dict = json.load(f)

    assert sys.argv[1].upper() in dict.keys(),
       "Invalid argument. Please make sure your source argument is either CNAC, RCIV or SRAG."
       
    dict_item = dict[sys.argv[1].upper()]
    main(dict_item['source_path'], dict_item['source_args'])
```

2021-05-27 00:01 UTC, brbraziel approved these changes

2021-05-27 11:24 UTC, davikawasaki approved these changes

2021-05-27 11:24 UTC, merged